### ISSUE TITLE
Byte-range support

### ISSUE THREAD

**Issue by bonddim** [Azure/aks-app-routing-operator#183]
Hi,
How to enable byte-range support on ingress resource?

On [kubernetes/ingress-nginx ](https://github.com/kubernetes/ingress-nginx) it can be enabled with annotation, but this does not work with addon controller
```yaml
annotations:
  nginx.ingress.kubernetes.io/configuration-snippet: |
    proxy_force_ranges on;
```
Current controller image:
```
mcr.microsoft.com/oss/kubernetes/ingress/nginx-ingress-controller:v1.9.4
```
