### ISSUE TITLE
Upgrade security context of controller container to be compatible with "Restricted" official pod security standard

### ISSUE THREAD

**Issue by gabor-one** [Azure/aks-app-routing-operator#191]
Currently, only the "runAsUser" option is set in the controller's container securityContext.
```yaml
securityContext:
            runAsUser: 101
```

Official Azure policies expect "allowPrivilegeEscalation" to be declared false.
[Kubernetes clusters should not allow container privilege escalation Azure policy](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F1c6e92c9-99f0-4e55-9cf2-0c234dc48f99)
[Gatekeeper template: k8sazurev3noprivilegeescalation](https://store.policy.core.windows.net/kubernetes/container-no-privilege-escalation/v3/template.yaml)

I propose to upgrade the securityContext to match the official "restricted" pod security standard.
Official pod security standards [documentation](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

Proposed securityContext:
```yaml
spec:
  template:
    spec:
      containers:
        - name: controller
           securityContext:
             runAsUser: 101
             allowPrivilegeEscalation: false
             seccompProfile:
               type: RuntimeDefault
             capabilities:
               drop:
                 - ALL
```
