### ISSUE TITLE
When using name `default` in CRD, the `controllerNamePrefix` is fixed to `nginx`

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/aks-app-routing-operator#286]
```bash
az aks approuting enable --resource-group $resourceGroup --name $clusterName --nginx None
```

Change `metadata.name` to the name other than `default` will not encounter the issue.
```yaml
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  controllerNamePrefix: testprefix
```
