### ISSUE TITLE
strict decoding error: unknown field "spec.defaultBackendService"

### ISSUE THREAD

**Issue by fluffy-cakes** [Azure/aks-app-routing-operator#311]
According to the [docs ](https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration#configuration-of-the-nginx-ingress-controller) I should be able to set the `defaultBackendService` settings, but I am prompted with an error:

`Error from server (BadRequest): error when creating ".\\testnginxcontroller.yml": NginxIngressController in version "v1alpha1" cannot be handled as a NginxIngressController: strict decoding error: unknown field "spec.defaultBackendService"`

I have tried editing the original `Nginxingresscontrollers` and creating my own as a test; neither work.

```yaml
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: asdf
spec:
  controllerNamePrefix: asdf
  ingressClassName: webapprouting.kubernetes.azure.com
  loadBalancerAnnotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  defaultBackendService:
    name: nginx
    namespace: app-routing-system
```

Looking at the schema, this should be possible:  https://github.com/Azure/aks-app-routing-operator/blob/main/config/crd/bases/approuting.kubernetes.azure.com_nginxingresscontrollers.yaml
