### ISSUE TITLE
strict decoding error: unknown field "spec.defaultSSLCertificate.forceSSLRedirect"

### ISSUE THREAD

**Issue by ivialex** [Azure/aks-app-routing-operator#361]
According to the [docs ](https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration#configuration-of-the-nginx-ingress-controller)I should be able to set the defaultSSLCertificate.forceSSLRedirect settings, but I am prompted with an error:

Error from server `strict decoding error: unknown field "spec.defaultSSLCertificate.forceSSLRedirect"`

The documentation in GitHub already exists the property forceSSLRedirect: https://github.com/Azure/aks-app-routing-operator/blob/main/config/crd/bases/approuting.kubernetes.azure.com_nginxingresscontrollers.yaml#L101

 ```
           defaultSSLCertificate:
                description: |-
                  DefaultSSLCertificate defines whether the NginxIngressController should use a certain SSL certificate by default.
                  If this field is omitted, no default certificate will be used.
                maxProperties: 2
                properties:
                  forceSSLRedirect:
                    default: false
                    description: ForceSSLRedirect is a flag that sets the global value
                      of redirects to HTTPS if there is a defined DefaultSSLCertificate
                    type: boolean
                  keyVaultURI:
                    description: Secret in the form of a Key Vault URI
                    type: string
```
However, when I run the following command it is not showing the property `forceSSLRedirect` : 

`kubectl get crd nginxingresscontrollers.approuting.kubernetes.azure.com -o yaml`

**Output:**

```
 defaultSSLCertificate:
                description: DefaultSSLCertificate defines whether the NginxIngressController
                  should use a certain SSL certificate by default. If this field is
                  omitted, no default certificate will be used.
                maxProperties: 1
                properties:
                  keyVaultURI:
                    description: Secret in the form of a Key Vault URI
                    type: string
                  secret:
                    description: Secret is a struct that holds the name and namespace
                      fields used for the default ssl secret
                    properties:
                      name:
                        maxLength: 253
                        minLength: 1
                        pattern: ^[a-z0-9][-a-z0-9\.]*[a-z0-9]$
                        type: string
                      namespace:
                        maxLength: 253
                        minLength: 1
                        pattern: ^[a-z0-9][-a-z0-9\.]*[a-z0-9]$
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                type: object
```

and here is my `NginxIngressController`

```
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal-grpc-subnet
spec:
  ingressClassName: nginx-internal-grpc-subnet
  controllerNamePrefix: nginx-internal-grpc-subnet
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet-10"
  defaultSSLCertificate: 
    forceSSLRedirect: true
    keyVaultURI: "https://lab1-appdep-kv.vault.azure.net/certificates/lab1-app/"
    # secret:
    #   name: "lab1"
    #   namespace: "app-routing-system"
```

Then, how to fix the CRD in my AKS Cluster?

Thanks!

**Comment by sabbour** [comment]
The release of the app-routing-operator with this functionality hasn't rolled out yet. This is an error in docs.
I will update the docs to include a reference to which functionality is available for which version of Kubernetes.

In the meantime, you can remove `forceSSLRedirect` from the `NginxIngressController` and as a workaround, you will need to add it as an annotation on individual ingress resources like:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: my-ingress
 annotations:
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```
