### ISSUE TITLE
[FeatureRequest] Tolerations and NodeSelector

### ISSUE THREAD

**Issue by Sokratis1904** [Azure/aks-app-routing-operator#408]
I would like to propose the addition of support for Tolerations and NodeSelector in the Nginx Ingress Controller. This feature is essential for users like myself who need to deploy resources on dedicated NodePools. By allowing Tolerations and NodeSelectors to be configured, we can ensure that the Nginx Ingress Controller can effectively manage traffic on specific nodes that meet our resource and performance requirements.

```
tolerations:
  - key: infra
    operator: Equal
    value: "true"
    effect: NoSchedule
  nodeSelector:
    type: infra
```
